channels:
- conda-forge
dependencies:
- python=3.13.9
- pip<=25.3
- pip:
  - mlflow==3.14.0
  - bottleneck==1.4.2
  - dask==2025.11.0
  - lz4==4.4.5
  - numpy==2.3.5
  - numpydoc==1.9.0
  - pandas==2.3.3
  - psutil==7.0.0
  - pyarrow==21.0.0
  - pytest==8.4.2
  - scikit-learn==1.7.2
  - scipy==1.16.3
  - skops==0.14.0
  - tblib==3.1.0
  - xarray==2025.10.1
name: mlflow-env
